### PR TITLE
Remove corresponding tasks from plans when a problem is deleted

### LINKED ISSUE #149: Deleting problems does not remove corresponding tasks
- This gives null pointer exceptions in next launch of AlgoBase

### PR DESCRIPTION
**Pull request by jiayushe**
- Remove corresponding tasks from plans when a problem is deleted (Fix #149)

### CODE REVIEW

File: src/main/java/seedu/algobase/model/ModelManager.java [hunk 1]
```diff
@@ -51,7 +52,8 @@ public ModelManager(ReadOnlyAlgoBase algoBase, ReadOnlyUserPrefs userPrefs) {
         this.userPrefs = new UserPrefs(userPrefs);
         filteredProblems = new FilteredList<>(this.algoBase.getProblemList());
         filteredTags = new FilteredList<>(this.algoBase.getTagList());
-        sortedProblems = (new SortedList<>(filteredProblems));
+        sortedProblems = new SortedList<>(filteredProblems);
+        sortedProblems.setComparator(SortCommand.PROBLEM_NAME_COMPARATOR);
```
Comment (le0tan) [inline src/main/java/seedu/algobase/model/ModelManager.java:56]: Why added this line?

Comment (jiayushe) [reply src/main/java/seedu/algobase/model/ModelManager.java:56]: To give the problem list a default comparator. If not the order of the problems is a bit indeterministic.

**Review by le0tan — APPROVED** [review]
LGTM. Please update the test commands in the shared folder as well.
