### PR TITLE
Fix add and edit empty tag bug.

### LINKED ISSUE #182: Can add problem with empty tag
Shouldn't allow empty tag content.

<hr><sub>[original: TSAI-HSIAO-HAN/ped#6]<br/>
</sub>

### LINKED ISSUE #183: edit with tag
This command with edit to add a tag and clear all tags will result in adding a empty tag.
Should also specify in document cannot use two tag's command in same time.
Or a better way is to seperate the clear all tag command with edit command.

<hr><sub>[original: TSAI-HSIAO-HAN/ped#8]<br/>
</sub>

### PR DESCRIPTION
**Pull request by LuWenQ**
closes #182 , closes #183

### CODE REVIEW

File: src/main/java/seedu/algobase/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -205,7 +205,7 @@ public static Source parseSource(String source) throws ParseException {
     public static Tag parseTag(String tag) throws ParseException {
         requireNonNull(tag);
         String trimmedTag = tag.trim();
-        if (!Tag.isValidTagName(trimmedTag)) {
+        if (!Tag.isValidTagName(trimmedTag) || tag.equals("")) {
```
Comment (le0tan) [inline src/main/java/seedu/algobase/logic/parser/ParserUtil.java]: You should use `.isEmpty` or `.isBlank` instead.

**Review by le0tan — CHANGES_REQUESTED** [review]

**Review by le0tan — APPROVED** [review]
