### PR TITLE
Bug fixes and edit GUI 

### LINKED ISSUE #156: Make Details Tabs responsive
The width for the textfields are fixed

### LINKED ISSUE #161: Double clicking plans won't change current plan

### LINKED ISSUE #168: In details tab,  remark part of problem is too small and can only controled by the caret.
In details tab,  remark part of problem is too small and can only controled by the caret.
And the caret is not shown in the UI.
For V1.3.1

### LINKED ISSUE #169: The image of AlgoBase in UG is not up-to-date
The image of AlgoBase in UG is not up-to-date
Especially the pie-chart part is different

### LINKED ISSUE #172: `clear` would result in uncaught exception
Logging message:

```
INFO: ----------------[USER COMMAND][clear]
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException
	at seedu.algobase.commons.core.index.Index.<init>(Index.java:20)
	at seedu.algobase.commons.core.index.Index.fromZeroBased(Index.java:38)
	at seedu.algobase.ui.details.DetailsTabPane$1.changed(DetailsTabPane.java:102)
	at seedu.algobase.ui.details.DetailsTabPane$1.changed(DetailsTabPane.java:99)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:69)
	at javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:215)
	at javafx.scene.control.SingleSelectionModel.clearSelection(SingleSelectionModel.java:68)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$0(TabPane.java:709)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at com.sun.javafx.collections.ObservableListWrapper.clear(ObservableListWrapper.java:157)
	at seedu.algobase.ui.details.DetailsTabPane.clearTabs(DetailsTabPane.java:123)
	at seedu.algobase.ui.details.DetailsTabPane$2.onChanged(DetailsTabPane.java:114)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$0(FXCollections.java:955)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at seedu.algobase.model.gui.UniqueTabDataList.setTabsData(UniqueTabDataList.java:132)
	at seedu.algobase.model.gui.TabManager.resetData(TabManager.java:42)
	at seedu.algobase.model.gui.GuiState.resetData(GuiState.java:42)
	at seedu.algobase.model.AlgoBase.resetData(AlgoBase.java:71)
	at seedu.algobase.model.ModelManager.setAlgoBase(ModelManager.java:111)
	at seedu.algobase.logic.commands.ClearCommand.execute(ClearCommand.java:25)
	at seedu.algobase.logic.LogicManager.execute(LogicManager.java:53)
	at seedu.algobase.ui.MainWindow.executeCommand(MainWindow.java:231)
	at seedu.algobase.ui.CommandBox.handleCommandEntered(CommandBox.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8879)
	at com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:184)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:330)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
	at javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at com.sun.glass.ui.View.notifyKey(View.java:971)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
Nov 01, 2019 5:05:05 PM seedu.algobase.ui.MainWindow executeCommand
INFO: Result: AlgoBase has been cleared.
```

### LINKED ISSUE #190: UI doesnt match
The Ui doesnt match the jar file provided

compare to:

<hr><sub>[original: honhaochen/ped#4]<br/>
</sub>

### LINKED ISSUE #193: Clear doesnt clear the entries on PlanTab
<hr><sub>[original: honhaochen/ped#7]<br/>
</sub>

### LINKED ISSUE #196: "CurrentPlan" Tab
Anyway to display the "CurrentPlan" tab by clicking the plans in PlanTab?

Right now it just switches automatically on add and edit

<hr><sub>[original: honhaochen/ped#10]<br/>
</sub>

### PR DESCRIPTION
**Pull request by tiuweehan**
Fix #156
Fix #161 
Fix #168 
Fix #169 
Fix #172
Fix #190 
Fix #193
Fix #196

Make `ProblemDetails` and `PlanDetails` editable and deletable
Update UG and DG

### CODE REVIEW

File: src/main/java/seedu/algobase/model/AlgoBase.java [hunk 1]
```diff
@@ -267,6 +267,13 @@ public void removePlan(Plan key) {
         plans.remove(key);
     }
 
+    /**
+     Clear the list of plans
```
Comment (le0tan) [inline src/main/java/seedu/algobase/model/AlgoBase.java]: Comment format is incorrect.

File: src/main/java/seedu/algobase/ui/MainWindow.java [hunk 2]
```diff
@@ -238,4 +241,32 @@ private CommandResult executeCommand(String commandText) throws CommandException
...
+                handleHelp();
+            }
+
+            if (uiActionResult.isExit()) {
+                handleExit();
+            }
+
+            return uiActionResult;
+        } catch (UiActionException | ParseException e) {
+            resultDisplay.setFeedbackToUser(e.getMessage());
```
Comment (le0tan) [inline src/main/java/seedu/algobase/ui/MainWindow.java:268]: Probably it's better to display UI results at the bottom of the app (so that `resultDisplay` always shows feedback from CLI commands`

File: src/main/java/seedu/algobase/ui/action/UiParser.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package seedu.algobase.ui.action;
+
+import seedu.algobase.logic.parser.exceptions.ParseException;
+
+/**
+ * Represents a Parser that is able to parse user input into a {@code Command} of type {@code T}.
+ */
+public interface UiParser<T extends UiAction> {
```
Comment (le0tan) [inline src/main/java/seedu/algobase/ui/action/UiParser.java:8]: If `UiParser` parses user input into a `Command` of type `T` then here should be `<T extends Command>`? Probably the description is a bit off?

**Review by le0tan — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/algobase/ui/MainWindow.java (hunk 2 above)
Comment (tiuweehan) [reply src/main/java/seedu/algobase/ui/MainWindow.java:268]: I agree that a snackbar would be useful, but I think it is fine if significant changes are shown to the user, e.g. editing and deleting problems, as compared to switching and opening tabs.

File: src/main/java/seedu/algobase/ui/action/UiParser.java (hunk 3 above)
Comment (tiuweehan) [reply src/main/java/seedu/algobase/ui/action/UiParser.java:8]: I was using `Command` initially but switched. Good catch!

**Review by le0tan — APPROVED** [review]
